- name: Install mySql for Expense
  hosts: localhost
  become: true

  vars:
    my_login_host: "praveen.store"

  vars_prompt:
    name: my_login_password
    prompt: "Please Enter your login password: "
    private: false

  tasks:
    - name: Install Mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Start and Enable mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

     - name: Install Python Mysql Dependencies
       ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: pip3.9

    - name: check DB Connection
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ my_login_password }}"
        login_host: "{{ my_login_host }}"
        filter: version
      ignore_errors: yes
      register: mysql_connection_output

    - name: print output of mysql_connection_output
      ansible.builtin.debug:
        msg: "Output: {{mysql_connection_output}}"
